// types.js

export const SEARCH_WEATHER_REQUEST = 'SEARCH_WEATHER_REQUEST';
export const SEARCH_WEATHER_SUCCESS = 'SEARCH_WEATHER_SUCCESS';
export const SEARCH_WEATHER_FAILURE = 'SEARCH_WEATHER_FAILURE';

export const GET_FORECAST_REQUEST = 'GET_FORECAST_REQUEST';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const GET_FORECAST_FAILURE = 'GET_FORECAST_FAILURE';
